# Generated by Django 5.0.14 on 2026-07-04 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset_tag', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MOBILE_PHONE', 'Mobile Phone'), ('VEHICLE', 'Vehicle'), ('ACCESS_CARD', 'Access Card'), ('MONITOR', 'Monitor'), ('PRINTER', 'Printer'), ('OTHER', 'Other')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('IN_MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20)),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('condition_on_assign', models.CharField(blank=True, max_length=10)),
                ('condition_on_return', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reported_date', models.DateField()),
                ('description', models.TextField()),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=15)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='LostAssetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reported_date', models.DateField()),
                ('circumstances', models.TextField()),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('WRITTEN_OFF', 'Written Off')], default='REPORTED', max_length=15)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
    ]
