# Generated by Django 5.0.14 on 2026-07-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, default=587, null=True),
        ),
    ]
