# Generated by Django 5.0.14 on 2026-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_emailsettings_smtp_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('extra_recipients', models.JSONField(blank=True, default=list, help_text='Additional email addresses to include, beyond every active HR Manager/Super Admin.')),
            ],
            options={
                'verbose_name': 'Weekly Report Settings',
                'verbose_name_plural': 'Weekly Report Settings',
            },
        ),
    ]
