# Generated by Django 5.0.14 on 2026-07-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0003_employee_device_user_id'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('ZKTECO', 'ZKTeco Biometric')], default='ZKTECO', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=4370)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='organization.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.device'),
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('event', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('GPS', 'GPS'), ('QR', 'QR Code'), ('BIOMETRIC', 'Fingerprint'), ('FACE', 'Face Recognition')], default='BIOMETRIC', max_length=20)),
                ('raw_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='attendance.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='attendance__employe_cf69c6_idx')],
                'unique_together': {('employee', 'device', 'timestamp')},
            },
        ),
    ]
