# Generated by Django 5.0.14 on 2026-07-08 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_syncagent_syncevent'),
        ('employees', '0004_employee_bank_account_number_employee_bank_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend_days', models.JSONField(default=list, help_text='ISO weekday numbers (1=Mon..7=Sun) treated as non-working for employees with no work shift assigned.')),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_to_approve', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='supervisor_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='supervisor_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='SKIPPED', max_length=20),
        ),
    ]
