# Generated by Django 5.0.14 on 2026-07-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('ZKTECO', 'ZKTeco Biometric'), ('HIKVISION', 'Hikvision Access Control')], default='ZKTECO', max_length=20),
        ),
    ]
