# Generated by Django 5.0.14 on 2026-07-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a company-wide holiday.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.branch'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'),
        ),
    ]
