# Generated by Django 5.0.14 on 2026-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device_user_id',
            field=models.CharField(blank=True, help_text='User ID as enrolled on the biometric attendance device (e.g. ZKTeco), used to match clock-in/out events.', max_length=20, null=True, unique=True),
        ),
    ]
