# Generated by Django 5.0.14 on 2026-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text='No fixed hours — clock-ins/outs are never marked late or an early departure, and no overtime is computed. start_time/end_time are ignored for attendance evaluation (kept only for display) when this is on.'),
        ),
    ]
