# Generated by Django 5.0.14 on 2026-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('CV', 'CV'), ('EMPLOYMENT_CONTRACT', 'Employment Contract'), ('ACADEMIC_CERTIFICATE', 'Academic Certificate'), ('PROFESSIONAL_CERTIFICATE', 'Professional Certificate'), ('DRIVING_LICENSE', 'Driving License'), ('NDA', 'NDA'), ('KRA_CERTIFICATE', 'KRA Certificate'), ('NSSF_DOCUMENT', 'NSSF Document'), ('SHIF_NHIF_DOCUMENT', 'SHIF/NHIF Document'), ('COMPANY_POLICY', 'Company Policy'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_company_document', models.BooleanField(default=False, help_text='If true, visible to every employee via employee self-service.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
