# Generated by Django 5.0.14 on 2026-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_type', models.CharField(choices=[('WARNING_LETTER', 'Warning Letter'), ('SHOW_CAUSE_LETTER', 'Show Cause Letter'), ('SUSPENSION', 'Suspension'), ('TERMINATION', 'Termination'), ('OTHER', 'Other')], max_length=20)),
                ('issued_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='disciplinary/documents/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_type', models.CharField(choices=[('WARNING', 'Warning'), ('SHOW_CAUSE', 'Show Cause'), ('SUSPENSION', 'Suspension'), ('HEARING', 'Hearing'), ('TERMINATION', 'Termination')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('incident_date', models.DateField()),
                ('resolution', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scheduled_date', models.DateTimeField()),
                ('outcome', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
