# Generated by Django 5.0.14 on 2026-07-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinary', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='disciplinarycase',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_cases', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='disciplinarycase',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='disciplinary.disciplinarycase'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='disciplinary.disciplinarycase'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='panel_members',
            field=models.ManyToManyField(blank=True, related_name='+', to='employees.employee'),
        ),
    ]
