# Generated by Django 5.0.14 on 2026-07-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_device_user_id'),
        ('leave', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapprovalstep',
            name='approver_role',
        ),
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='entered_at',
            field=models.DateTimeField(blank=True, help_text='When this step became the active pending step.', null=True),
        ),
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='resolver_type',
            field=models.CharField(blank=True, choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('SKIP_LEVEL_MANAGER', "Manager's Manager (N levels up)"), ('DEPARTMENT_HEAD', 'Department Head'), ('BRANCH_MANAGER', 'Branch Manager'), ('SPECIFIC_EMPLOYEE', 'Specific Employee'), ('SYSTEM_ROLE', 'Anyone with a System Role')], max_length=30),
        ),
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='system_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Administrator'), ('HR_MANAGER', 'HR Manager'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee')], max_length=30),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='allow_negative_balance',
            field=models.BooleanField(default=False, help_text='If enabled, employees may submit requests exceeding their remaining balance.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('RETURNED', 'Returned for Correction')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('step_order', models.PositiveIntegerField()),
                ('name', models.CharField(help_text="Admin-facing label, e.g. 'Head of Department'.", max_length=100)),
                ('resolver_type', models.CharField(choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('SKIP_LEVEL_MANAGER', "Manager's Manager (N levels up)"), ('DEPARTMENT_HEAD', 'Department Head'), ('BRANCH_MANAGER', 'Branch Manager'), ('SPECIFIC_EMPLOYEE', 'Specific Employee'), ('SYSTEM_ROLE', 'Anyone with a System Role')], max_length=30)),
                ('system_role', models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Administrator'), ('HR_MANAGER', 'HR Manager'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee')], max_length=30)),
                ('skip_levels', models.PositiveIntegerField(default=1, help_text="For 'Manager's Manager' — how many reporting-manager hops to walk up.")),
                ('min_days', models.DecimalField(blank=True, decimal_places=1, help_text="Only include this step if the request's total days is at least this.", max_digits=5, null=True)),
                ('max_days', models.DecimalField(blank=True, decimal_places=1, help_text="Only include this step if the request's total days is at most this.", max_digits=5, null=True)),
                ('reminder_after_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('escalation_after_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('escalate_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('specific_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='source_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leave.workflowstep'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="Used as a fallback when no other template's assignment rules match.")),
                ('priority', models.PositiveIntegerField(default=0, help_text='When multiple templates match a request, the highest priority wins.')),
                ('require_all_parallel_approvers', models.BooleanField(default=False, help_text='When a step has multiple approvers (same order), require all of them rather than any one.')),
                ('employment_types', models.JSONField(blank=True, default=list, help_text='List of Employee.EmploymentType values. Empty = applies to any.')),
                ('branches', models.ManyToManyField(blank=True, related_name='leave_workflow_templates', to='organization.branch')),
                ('departments', models.ManyToManyField(blank=True, related_name='leave_workflow_templates', to='organization.department')),
                ('leave_types', models.ManyToManyField(blank=True, related_name='workflow_templates', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='leave.workflowtemplate'),
        ),
    ]
